"""Document 1 horizontal indicator collection domain."""

from doxagent.horizontal_collection.artifacts import HorizontalCollectionManifestRepository
from doxagent.horizontal_collection.registry import (
    METRIC_REGISTRY_VERSION,
    REQUIRED_METRIC_IDS,
    TARGET_REGISTRY_VERSION,
    CollectionTargetRegistry,
    MetricRegistry,
    default_collection_target_registry,
    default_metric_registry,
)
from doxagent.horizontal_collection.schema import (
    CollectionMode,
    CollectionObservation,
    CollectionTargetDefinition,
    CollectionTargetStatus,
    EntityScope,
    HorizontalCollectionArtifactEnvelope,
    HorizontalCollectionManifest,
    HorizontalCollectionTargetResult,
    MetricDefinition,
    MetricRequirement,
    MetricValueType,
    ObjectRef,
    ObjectType,
    OutputPolicy,
    ProviderAttempt,
    ProviderCapabilityStatus,
    ResolverStatus,
    SourceRole,
    StateParameterIdentity,
    StateValueCurrentKey,
)

__all__ = [
    "CollectionMode",
    "CollectionObservation",
    "CollectionTargetDefinition",
    "CollectionTargetStatus",
    "EntityScope",
    "HorizontalCollectionArtifactEnvelope",
    "HorizontalCollectionManifest",
    "HorizontalCollectionManifestRepository",
    "HorizontalCollectionTargetResult",
    "MetricDefinition",
    "MetricRegistry",
    "MetricRequirement",
    "MetricValueType",
    "ObjectRef",
    "ObjectType",
    "OutputPolicy",
    "ProviderAttempt",
    "ProviderCapabilityStatus",
    "ResolverStatus",
    "SourceRole",
    "StateParameterIdentity",
    "StateValueCurrentKey",
    "CollectionTargetRegistry",
    "METRIC_REGISTRY_VERSION",
    "REQUIRED_METRIC_IDS",
    "TARGET_REGISTRY_VERSION",
    "default_collection_target_registry",
    "default_metric_registry",
]
