ARG BASE_IMAGE=doxagent-v2:production
FROM ${BASE_IMAGE}

USER root
RUN apt-get update \
    && apt-get install -y --no-install-recommends xvfb x11vnc locales tzdata util-linux \
    && sed -i 's/^# *en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen \
    && locale-gen en_US.UTF-8 \
    && groupadd --gid 10001 siteaccess \
    && useradd --uid 10001 --gid 10001 --home-dir /home/siteaccess \
         --create-home --shell /usr/sbin/nologin siteaccess \
    && rm -rf /var/lib/apt/lists/*
ENV LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 HOME=/home/siteaccess
COPY deploy/site-access-entrypoint.sh /usr/local/bin/site-access-entrypoint
RUN chmod 0755 /usr/local/bin/site-access-entrypoint
ENTRYPOINT ["/usr/local/bin/site-access-entrypoint"]
CMD ["python", "-m", "doxagent.site_strategy.cli", "run-server", "--host", "0.0.0.0", "--port", "8011"]
