#!/bin/sh
set -eu
for firewall in /usr/sbin/iptables /usr/sbin/ip6tables; do
 "$firewall" -C INPUT ! -i lo -p tcp -m multiport --dports 4001,4002 -j DROP 2>/dev/null || "$firewall" -I INPUT 1 ! -i lo -p tcp -m multiport --dports 4001,4002 -j DROP
done
