"""Phase 1 domain contract models."""

from doxagent.models.blackboard import (
    BeliefStateSnapshot,
    BlackboardPatch,
    BlackboardTarget,
    CommitLogEntry,
    Delegation,
    EvidenceRef,
    Objection,
    WorkingMemoryEntry,
)
from doxagent.models.common import (
    AgentName,
    AgentRole,
    DelegationStatus,
    DocumentType,
    EvidenceSourceType,
    ExpectationDirection,
    ObjectionSeverity,
    ObjectionStatus,
    PatchOperation,
    PolicyActionType,
    ResultStatus,
    TaskType,
    ValidationStatus,
)
from doxagent.models.contracts import (
    AgentError,
    AgentPermissions,
    AgentResult,
    AgentTask,
    RunMetadata,
    ToolCallSummary,
)
from doxagent.models.documents import (
    EventMonitoringDirection,
    ExpectationUnitDocument,
    GlobalResearchDocument,
    KnownEvent,
    KnownEventsDocument,
    MonitoringConfigDocument,
    MonitoringItem,
    MonitoringPolicyDocument,
    MonitoringPolicyRule,
    PriceReaction,
    RealizedFact,
    ResearchSection,
    VariableStatus,
)
from doxagent.models.ids import NonEmptyStr, new_id
from doxagent.models.validation import (
    can_promote_target,
    has_blocking_delegations,
    has_unresolved_objections,
    same_target,
)
from doxagent.skills.schema import SkillBundle, SkillSummary

__all__ = [
    "AgentError",
    "AgentName",
    "AgentPermissions",
    "AgentResult",
    "AgentRole",
    "AgentTask",
    "BeliefStateSnapshot",
    "BlackboardPatch",
    "BlackboardTarget",
    "CommitLogEntry",
    "Delegation",
    "DelegationStatus",
    "DocumentType",
    "EventMonitoringDirection",
    "EvidenceRef",
    "EvidenceSourceType",
    "ExpectationDirection",
    "ExpectationUnitDocument",
    "GlobalResearchDocument",
    "KnownEvent",
    "KnownEventsDocument",
    "MonitoringConfigDocument",
    "MonitoringItem",
    "MonitoringPolicyDocument",
    "MonitoringPolicyRule",
    "NonEmptyStr",
    "Objection",
    "ObjectionSeverity",
    "ObjectionStatus",
    "PatchOperation",
    "PolicyActionType",
    "PriceReaction",
    "RealizedFact",
    "ResearchSection",
    "ResultStatus",
    "RunMetadata",
    "SkillBundle",
    "SkillSummary",
    "TaskType",
    "ToolCallSummary",
    "ValidationStatus",
    "VariableStatus",
    "WorkingMemoryEntry",
    "can_promote_target",
    "has_blocking_delegations",
    "has_unresolved_objections",
    "new_id",
    "same_target",
]
